### ISSUE TITLE
Dead links on wiki

### ISSUE THREAD

**Issue by erikcramerjr** [LETARTARE/GCV#1]
There are some dead links on the wiki main page.
Also, how do I download this program ?

**Comment by LETARTARE** [comment]
Hello,
thanks for dead links.
Can not you load the program now, because it is not finished: some parts are not operational.
Cordially.

**Comment by erikcramerjr** [comment]
Can I test with the working parts just want to move the axis now and cnc
something if that's possible. That's what GitHub is for no?

**Comment by erikcramerjr** [comment]
Can in contact you by email?
